name: Build API and push to ECR
on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/api-ecr.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-west-2"
          role-to-assume: "arn:aws:iam::104927514697:role/GitHub-OIDC"
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: setup repository
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-west-2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 104927514697.dkr.ecr.us-west-2.amazonaws.com/progate-hackathon-vod-gpt-api-main:latest
          context: ./api
          file: ./api/Dockerfile

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition pg-example-task-api-server --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: api-main-container
          image: 104927514697.dkr.ecr.us-west-2.amazonaws.com/progate-hackathon-vod-gpt-api-main:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: fargate-service
          cluster: pg-ecs-cluster
          wait-for-service-stability: true
